In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# Preporcess the data

data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
# Encode Categorical Variable
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [7]:
# One-hot encode geography
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
# Combine one-hot encoded columns with original data

data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
# Split the data into features and target

X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [12]:
## Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [14]:
# Save the encoders and scaler for later use

with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

# ANN Regression Problem Statement

In [15]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import  Dense

In [19]:
# Build the model 

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) #output layer for regression
])

#Compile the model

model.compile(optimizer='adam',loss="mean_absolute_error",metrics=['mae'])

model.summary()

WARNING:tensorflow:From d:\ANN Classification\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
# Set up the Tensorboard

import datetime
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard 

log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [21]:
## Setup Early Stopping

early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [22]:
## Training the model

history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 5ms/step - loss: 100364.9609 - mae: 100364.9609 - val_loss: 98467.4297 - val_mae: 98467.4297
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99448.2969 - mae: 99448.2969 - val_loss: 96626.5703 - val_mae: 96626.5703
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 96274.2656 - mae: 96274.2656 - val_loss: 91998.2422 - val_mae: 91998.2422
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 90131.3594 - mae: 90131.3594 - val_loss: 84440.7266 - val_mae: 84440.7266
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 81412.8828 - mae: 81412.8828 - val_loss: 75084.4609 - val_mae: 75084.4609
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 71662.1094 - mae: 71662.1094 - val_loss: 65922.0078 - val_mae: 65922.0078
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 62873.6602 - mae: 62873.6602 - val_loss: 58612.5195 - val_mae: 58612.5195
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 56490.6094 - mae: 56490.6094 - val_loss: 54010.7070 - val_mae: 54010.7070
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 52818.6914 - mae: 52818.6914 - val_loss: 51974.9492 - val_mae: 51974.9492
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 51199.8750 - mae: 51199.8750 - val_loss: 51359.3984 - val_mae: 51359.3984
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50638.7656 - mae: 50638.7656 - val_loss: 51147.2070 - val_mae: 51147.2070
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50418.5234 - mae: 50418.5234 - val_loss: 51062.9961 - val_mae: 51062.9961
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 50306.9492 - mae: 50306.9492 - val_loss: 50997.6641 - val_mae: 50997.6641
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 50229.4297 - mae: 50229.4297 - val_loss: 50950.8125 - val_mae: 50950.8125
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 50167.2891 - mae: 50167.2891 - val_loss: 50907.2852 - val_mae: 50907.2852
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 50117.2109 - mae: 50117.2109 - val_loss: 50854.6602 - val_mae: 50854.6602
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 50067.0625 - mae: 50067.0625 - val_loss: 50833.2734 - val_mae: 50833.2734
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 50027.8555 - mae: 50027.8555 - val_loss: 50792.9727 - val_mae: 50792.9727
Epoch 19/100
250/250 [==============================] - 1s 2ms/step - loss: 49984.6367 - mae: 49984.6367 - val_loss: 50759.7734 - val_mae: 50759.7734
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 49946.3945 - mae: 49946.3945 - val_loss: 50730.0117 - val_mae: 50730.0117
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 49914.8281 - mae: 49914.8281 - val_loss: 50704.6602 - val_mae: 50704.6602
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 49884.6133 - mae: 49884.6133 - val_loss: 50669.6914 - val_mae: 50669.6914
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49855.1875 - mae: 49855.1875 - val_loss: 50652.5195 - val_mae: 50652.5195
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 49827.8984 - mae: 49827.8984 - val_loss: 50621.4219 - val_mae: 50621.4219
Epoch 25/100
250/250 [==============================] - 1s 2ms/step - loss: 49802.4805 - mae: 49802.4805 - val_loss: 50605.6289 - val_mae: 50605.6289
Epoch 26/100
250/250 [==============================] - 1s 2ms/step - loss: 49781.6836 - mae: 49781.6836 - val_loss: 50587.9453 - val_mae: 50587.9453
Epoch 27/100
250/250 [==============================] - 1s 2ms/step - loss: 49762.3438 - mae: 49762.3438 - val_loss: 50579.7930 - val_mae: 50579.7930
Epoch 28/100
250/250 [==============================] - 1s 2ms/step - loss: 49743.3398 - mae: 49743.3398 - val_loss: 50562.5586 - val_mae: 50562.5586
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 49724.3906 - mae: 49724.3906 - val_loss: 50542.9414 - val_mae: 50542.9414
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49704.0977 - mae: 49704.0977 - val_loss: 50528.9062 - val_mae: 50528.9062
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49693.5078 - mae: 49693.5078 - val_loss: 50524.6367 - val_mae: 50524.6367
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49674.1875 - mae: 49674.1875 - val_loss: 50520.6602 - val_mae: 50520.6602
Epoch 33/100
250/250 [==============================] - 1s 2ms/step - loss: 49661.3086 - mae: 49661.3086 - val_loss: 50504.6992 - val_mae: 50504.6992
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 49648.4336 - mae: 49648.4336 - val_loss: 50498.6484 - val_mae: 50498.6484
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 49633.1719 - mae: 49633.1719 - val_loss: 50506.6562 - val_mae: 50506.6562
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 49623.2383 - mae: 49623.2383 - val_loss: 50486.4883 - val_mae: 50486.4883
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49611.1523 - mae: 49611.1523 - val_loss: 50486.7891 - val_mae: 50486.7891
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49598.2969 - mae: 49598.2969 - val_loss: 50463.8750 - val_mae: 50463.8750
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49588.2344 - mae: 49588.2344 - val_loss: 50466.3438 - val_mae: 50466.3438
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49578.7227 - mae: 49578.7227 - val_loss: 50452.4219 - val_mae: 50452.4219
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49571.8555 - mae: 49571.8555 - val_loss: 50441.2461 - val_mae: 50441.2461
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49562.3438 - mae: 49562.3438 - val_loss: 50448.0742 - val_mae: 50448.0742
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 49554.5469 - mae: 49554.5469 - val_loss: 50442.7891 - val_mae: 50442.7891
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 49548.1016 - mae: 49548.1016 - val_loss: 50427.4531 - val_mae: 50427.4531
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 49538.5391 - mae: 49538.5391 - val_loss: 50423.5586 - val_mae: 50423.5586
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49531.5547 - mae: 49531.5547 - val_loss: 50419.8477 - val_mae: 50419.8477
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49524.6641 - mae: 49524.6641 - val_loss: 50413.3320 - val_mae: 50413.3320
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 49516.1758 - mae: 49516.1758 - val_loss: 50416.3984 - val_mae: 50416.3984
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 49510.8555 - mae: 49510.8555 - val_loss: 50422.4141 - val_mae: 50422.4141
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 49499.2422 - mae: 49499.2422 - val_loss: 50409.7266 - val_mae: 50409.7266
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 49493.4961 - mae: 49493.4961 - val_loss: 50399.7656 - val_mae: 50399.7656
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49485.9414 - mae: 49485.9414 - val_loss: 50398.2344 - val_mae: 50398.2344
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49483.0547 - mae: 49483.0547 - val_loss: 50388.8203 - val_mae: 50388.8203
Epoch 54/100
250/250 [==============================] - 1s 2ms/step - loss: 49473.5898 - mae: 49473.5898 - val_loss: 50387.6719 - val_mae: 50387.6719
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 49470.3086 - mae: 49470.3086 - val_loss: 50393.5000 - val_mae: 50393.5000
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49467.0078 - mae: 49467.0078 - val_loss: 50393.0938 - val_mae: 50393.0938
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 49457.8008 - mae: 49457.8008 - val_loss: 50401.0625 - val_mae: 50401.0625
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49451.9648 - mae: 49451.9648 - val_loss: 50378.0234 - val_mae: 50378.0234
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 49449.7734 - mae: 49449.7734 - val_loss: 50383.6250 - val_mae: 50383.6250
Epoch 60/100
250/250 [==============================] - 1s 2ms/step - loss: 49441.3906 - mae: 49441.3906 - val_loss: 50384.6797 - val_mae: 50384.6797
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 49436.6875 - mae: 49436.6875 - val_loss: 50384.5430 - val_mae: 50384.5430
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 49431.5430 - mae: 49431.5430 - val_loss: 50385.6953 - val_mae: 50385.6953
Epoch 63/100
250/250 [==============================] - 1s 2ms/step - loss: 49424.8906 - mae: 49424.8906 - val_loss: 50391.4648 - val_mae: 50391.4648

In [23]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 6872), started 0:00:06 ago. (Use '!kill 6872' to kill it.)

In [29]:
# Evaluate model on the test data

test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 5ms/step - loss: 50378.0234 - mae: 50378.0234
Test MAE : 50378.0234375

In [30]:
model.save('regression_model.h5')

d:\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(